apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: github-tests-java-springboot-vijwdmlf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-tests-java-springboot-vijwdmlf 
  name: github-tests-java-springboot-vijwdmlf
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: github-tests-java-springboot-vijwdmlf 
